AWSTemplateFormatVersion: '2010-09-09'
Description: Finished IAM service role example
Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudformation_example_service_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              Service:
                - 'cloudformation.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: cloudformation_create_dynamo_table
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteTable'
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:CreateTable'
                Resource:
                  !Join
                    - ''
                    - - 'arn:aws:dynamodb:*:'
                      - !Ref AWS::AccountId
                      - ':table/sampleForIAMServiceRoles'

Outputs:
  ServiceRoleARN:
    Value: !GetAtt ServiceRole.Arn
