AWSTemplateFormatVersion: '2010-09-09'
Description: Simple template to create IAM service roles for
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: sampleForIAMServiceRoles
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'N'
        - AttributeName: 'description'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'description'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
